### ISSUE TITLE
Spammers friendly system

### ISSUE THREAD

**Issue by rainworm** [ivannovak/jpmaster77-s-Login-System-#4]
Any registered user can see other logged in users mail. This is heaven for spammers.

Advice: hide the email addresses of users. Users can comunicate via internal messages.
Or add profiles where users can define if they wan't to share their email address with everyone.

greetings,
rainworm

**Comment by ivannovak** [comment]
This issue is outside the scope of the intent of this system.  Feel free to implement this on your own system.

**Comment by rainworm** [comment]
OK, at least point it out in coments so people will know it's an issue.
