### ISSUE TITLE
eregi()

### ISSUE THREAD

**Issue by rainworm** [ivannovak/jpmaster77-s-Login-System-#6]
This function has been DEPRECATED as of PHP 5.3.0. Relying on this feature is highly discouraged.

greetings, 
rainworm

**Comment by ivannovak** [comment]
looks like preg_match does the same thing, I'll replace that and get it up shortly. Thanks for the heads up.

**Comment by rainworm** [comment]
No problem. I'm glad i'm helpfull. :)

**Comment by rainworm** [comment]
<pre>
I took a quick look at your source (haven't try it yet), but I would say the changes you have made don't work.
I think just changing the eregi() to preg_match() isn't good solution.

If we take a look at one of your code;
you changed "eregi("^([0-9a-z])+$", $subuser)" to "preg_match("^([0-9a-z])+$", $subuser)"

The correct way should be "preg_match("/^([0-9a-z])+$/i", $subuser)"

Why? In preg_match the first character in string is considered as delimiter and at the end you have to have the end of it.

greetings,
rainworm


</pre>
