### ISSUE TITLE
Critical! Internal mail system and SQL injection

### ISSUE THREAD

**Issue by rainworm** [ivannovak/jpmaster77-s-Login-System-#8]
In this internal mail system, you are taking raw input data and inserting it into a MySQL database. You have left yourself wide open for a security issue known as SQL Injection.

I strongly advise, to use MySql function "mysql_real_escape_string".

greetings,
rainworm

**Comment by ivannovak** [comment]
I will heed your advice and implement this, thanks! :)

**Comment by rainworm** [comment]
Great to hear that. :)
